/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "minifyjpeg.h"

bool_t
xdr_image_in (XDR *xdrs, image_in *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->src.src_val, (u_int *) &objp->src.src_len, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->src_len))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dst_len))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_image_out (XDR *xdrs, image_out *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->dst.dst_val, (u_int *) &objp->dst.dst_len, ~0))
		 return FALSE;
	return TRUE;
}
