/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MINIFYJPEG_H_RPCGEN
#define _MINIFYJPEG_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct image_in {
	struct {
		u_int src_len;
		char *src_val;
	} src;
	int src_len;
	int dst_len;
};
typedef struct image_in image_in;

struct image_out {
	struct {
		u_int dst_len;
		char *dst_val;
	} dst;
};
typedef struct image_out image_out;

#define MINIFYJPEG_PROG 0x20000008
#define MINIFYJPEG_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MINIFYJPEG_PROC 1
extern  enum clnt_stat minifyjpeg_proc_1(image_in , image_out *, CLIENT *);
extern  bool_t minifyjpeg_proc_1_svc(image_in , image_out *, struct svc_req *);
extern int minifyjpeg_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MINIFYJPEG_PROC 1
extern  enum clnt_stat minifyjpeg_proc_1();
extern  bool_t minifyjpeg_proc_1_svc();
extern int minifyjpeg_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_image_in (XDR *, image_in*);
extern  bool_t xdr_image_out (XDR *, image_out*);

#else /* K&R C */
extern bool_t xdr_image_in ();
extern bool_t xdr_image_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MINIFYJPEG_H_RPCGEN */
